-- Create enum types for statuses and roles
CREATE TYPE public.app_role AS ENUM ('host', 'guest', 'editor');
CREATE TYPE public.collaboration_status AS ENUM (
  'invited',
  'intake_completed',
  'scheduled',
  'recorded',
  'editing',
  'ready',
  'completed',
  'cancelled'
);
CREATE TYPE public.workspace_status AS ENUM ('active', 'archived');

-- Create profiles table for user data
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create user_roles table (separate from profiles for security)
CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role app_role NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);

-- Create workspaces table
CREATE TABLE public.workspaces (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status workspace_status NOT NULL DEFAULT 'active',
  welcome_message TEXT,
  welcome_video_url TEXT,
  max_reschedules INTEGER DEFAULT 2,
  reschedule_cutoff_hours INTEGER DEFAULT 24,
  external_storage_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create guest_profiles table (reusable across collaborations)
CREATE TABLE public.guest_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  bio TEXT,
  headshot_url TEXT,
  website_url TEXT,
  social_links JSONB DEFAULT '[]'::jsonb,
  topics TEXT[],
  pronunciation_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create collaborations table
CREATE TABLE public.collaborations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  host_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  guest_profile_id UUID REFERENCES public.guest_profiles(id) ON DELETE SET NULL,
  editor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  status collaboration_status NOT NULL DEFAULT 'invited',
  invite_token TEXT UNIQUE DEFAULT encode(gen_random_bytes(32), 'hex'),
  scheduled_date TIMESTAMPTZ,
  prep_date TIMESTAMPTZ,
  recorded_date TIMESTAMPTZ,
  editing_deadline TIMESTAMPTZ,
  delivery_date TIMESTAMPTZ,
  file_references JSONB DEFAULT '[]'::jsonb,
  posting_checklist JSONB DEFAULT '[]'::jsonb,
  reschedule_count INTEGER DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create tasks table (auto-generated by status)
CREATE TABLE public.tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  collaboration_id UUID NOT NULL REFERENCES public.collaborations(id) ON DELETE CASCADE,
  assigned_role app_role NOT NULL,
  assigned_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT,
  is_completed BOOLEAN DEFAULT false,
  is_skipped BOOLEAN DEFAULT false,
  due_date TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create workspace_members table for editor assignments
CREATE TABLE public.workspace_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role app_role NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, user_id)
);

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collaborations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_members ENABLE ROW LEVEL SECURITY;

-- Create security definer function to check roles
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id
      AND role = _role
  )
$$;

-- Create function to check workspace membership
CREATE OR REPLACE FUNCTION public.is_workspace_member(_user_id UUID, _workspace_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.workspaces WHERE id = _workspace_id AND owner_id = _user_id
    UNION
    SELECT 1 FROM public.workspace_members WHERE workspace_id = _workspace_id AND user_id = _user_id
  )
$$;

-- Create function to check collaboration access
CREATE OR REPLACE FUNCTION public.can_access_collaboration(_user_id UUID, _collaboration_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.collaborations c
    WHERE c.id = _collaboration_id
    AND (
      c.host_id = _user_id
      OR c.editor_id = _user_id
      OR EXISTS (
        SELECT 1 FROM public.guest_profiles gp 
        WHERE gp.id = c.guest_profile_id AND gp.user_id = _user_id
      )
    )
  )
$$;

-- Profiles policies
CREATE POLICY "Users can view their own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- User roles policies (read-only for users, managed by triggers)
CREATE POLICY "Users can view their own roles"
  ON public.user_roles FOR SELECT
  USING (auth.uid() = user_id);

-- Workspaces policies
CREATE POLICY "Owners can view their workspaces"
  ON public.workspaces FOR SELECT
  USING (owner_id = auth.uid() OR public.is_workspace_member(auth.uid(), id));

CREATE POLICY "Users can create workspaces"
  ON public.workspaces FOR INSERT
  WITH CHECK (owner_id = auth.uid());

CREATE POLICY "Owners can update their workspaces"
  ON public.workspaces FOR UPDATE
  USING (owner_id = auth.uid());

CREATE POLICY "Owners can delete their workspaces"
  ON public.workspaces FOR DELETE
  USING (owner_id = auth.uid());

-- Guest profiles policies
CREATE POLICY "Guests can view their own profile"
  ON public.guest_profiles FOR SELECT
  USING (
    user_id = auth.uid() 
    OR EXISTS (
      SELECT 1 FROM public.collaborations c
      WHERE c.guest_profile_id = guest_profiles.id
      AND (c.host_id = auth.uid() OR c.editor_id = auth.uid())
    )
  );

CREATE POLICY "Guests can update their own profile"
  ON public.guest_profiles FOR UPDATE
  USING (user_id = auth.uid());

CREATE POLICY "Users can create guest profiles"
  ON public.guest_profiles FOR INSERT
  WITH CHECK (true);

-- Collaborations policies
CREATE POLICY "Users can view collaborations they are part of"
  ON public.collaborations FOR SELECT
  USING (public.can_access_collaboration(auth.uid(), id));

CREATE POLICY "Hosts can create collaborations"
  ON public.collaborations FOR INSERT
  WITH CHECK (host_id = auth.uid());

CREATE POLICY "Hosts can update collaborations"
  ON public.collaborations FOR UPDATE
  USING (host_id = auth.uid() OR editor_id = auth.uid());

CREATE POLICY "Hosts can delete collaborations"
  ON public.collaborations FOR DELETE
  USING (host_id = auth.uid());

-- Allow public access to collaborations by invite token (for guest signup)
CREATE POLICY "Anyone can view collaboration by invite token"
  ON public.collaborations FOR SELECT
  USING (invite_token IS NOT NULL);

-- Tasks policies
CREATE POLICY "Users can view tasks for their collaborations"
  ON public.tasks FOR SELECT
  USING (public.can_access_collaboration(auth.uid(), collaboration_id));

CREATE POLICY "Assigned users can update their tasks"
  ON public.tasks FOR UPDATE
  USING (
    assigned_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.collaborations c
      WHERE c.id = collaboration_id AND c.host_id = auth.uid()
    )
  );

CREATE POLICY "System can create tasks"
  ON public.tasks FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.collaborations c
      WHERE c.id = collaboration_id AND c.host_id = auth.uid()
    )
  );

-- Workspace members policies
CREATE POLICY "Workspace owners can manage members"
  ON public.workspace_members FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.workspaces w
      WHERE w.id = workspace_id AND w.owner_id = auth.uid()
    )
  );

CREATE POLICY "Members can view their membership"
  ON public.workspace_members FOR SELECT
  USING (user_id = auth.uid());

-- Create trigger for auto-updating timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_workspaces_updated_at
  BEFORE UPDATE ON public.workspaces
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_guest_profiles_updated_at
  BEFORE UPDATE ON public.guest_profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_collaborations_updated_at
  BEFORE UPDATE ON public.collaborations
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_tasks_updated_at
  BEFORE UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Create trigger to auto-create profile and assign host role on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Create profile
  INSERT INTO public.profiles (user_id, full_name)
  VALUES (NEW.id, NEW.raw_user_meta_data ->> 'full_name');
  
  -- Assign host role by default (users can be hosts)
  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'host');
  
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Create indexes for performance
CREATE INDEX idx_workspaces_owner ON public.workspaces(owner_id);
CREATE INDEX idx_collaborations_workspace ON public.collaborations(workspace_id);
CREATE INDEX idx_collaborations_host ON public.collaborations(host_id);
CREATE INDEX idx_collaborations_guest_profile ON public.collaborations(guest_profile_id);
CREATE INDEX idx_collaborations_status ON public.collaborations(status);
CREATE INDEX idx_collaborations_invite_token ON public.collaborations(invite_token);
CREATE INDEX idx_tasks_collaboration ON public.tasks(collaboration_id);
CREATE INDEX idx_tasks_assigned_user ON public.tasks(assigned_user_id);
CREATE INDEX idx_guest_profiles_user ON public.guest_profiles(user_id);
CREATE INDEX idx_workspace_members_workspace ON public.workspace_members(workspace_id);
CREATE INDEX idx_workspace_members_user ON public.workspace_members(user_id);